<?php

namespace PHPExiftool\Driver;

require_once dirname(__FILE__) . '/../../../../lib/PHPExiftool/Driver/TagFactory.php';

/**
 * Test class for TagFactory.
 * Generated by PHPUnit on 2012-03-12 at 20:17:53.
 */
class TagFactoryTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var TagFactory
   */
  protected $object;


  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGetFromRDFTagname().
   */
  public function testGetFromRDFTagname()
  {
    $tag = TagFactory::getFromRDFTagname('IPTC:SupplementalCategories');
    $this->assertInstanceOf('\PHPExiftool\Driver\Tag\IPTC\SupplementalCategories', $tag);

    $tag = TagFactory::getFromRDFTagname('XMPExif:ApertureValue');
    $this->assertInstanceOf('\PHPExiftool\Driver\Tag\XMPExif\ApertureValue', $tag);

    try
    {
      $tag = TagFactory::getFromRDFTagname('XMPExif:AnunexistingTag');
      $this->fail('Should raise a TagUnknown exception');
    }
    catch(\PHPExiftool\Exception\TagUnknown $e)
    {

    }
  }

}

?>
