<?php

namespace PHPExiftool\Driver\Tag\RealMDPR;

class Software extends \PHPExiftool\Driver\Tag
{

    protected $Id = 'Generated By';

    protected $Name = 'Software';

    protected $FullName = 'Real::FileInfo';

    protected $GroupName = 'Real-MDPR';

    protected $g0 = 'Real';

    protected $g1 = 'Real-MDPR';

    protected $g2 = 'Video';

    protected $Type = '?';

    protected $Writable = false;

    protected $Description = 'Software';

}
